# ------------------------------------------------------------------------------
# Copyright (c) Ron MacNeil <macro@hotmail.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
# ------------------------------------------------------------------------------


DOTNETFRAMEWORK_MONO_GENERATIONS := 40 35 30 20

DOTNETFRAMEWORK_MONO_MONO := $(strip $(call MAKE_Shell,which mono 2>&-))
DOTNETFRAMEWORK_MONO_MCS := $(strip $(call MAKE_Shell,which mcs 2>&-))
DOTNETFRAMEWORK_MONO_GMCS := $(strip $(call MAKE_Shell,which gmcs 2>&-))
DOTNETFRAMEWORK_MONO_DMCS := $(strip $(call MAKE_Shell,which dmcs 2>&-))

DOTNETFRAMEWORK_MONO_MCS_40 := $(DOTNETFRAMEWORK_MONO_DMCS)
DOTNETFRAMEWORK_MONO_MCS_35 := $(DOTNETFRAMEWORK_MONO_GMCS)
DOTNETFRAMEWORK_MONO_MCS_30 := $(DOTNETFRAMEWORK_MONO_GMCS)
DOTNETFRAMEWORK_MONO_MCS_20 := $(DOTNETFRAMEWORK_MONO_GMCS)

DOTNETFRAMEWORK_MONO_LANGVERSIONSWITCH_40 :=
DOTNETFRAMEWORK_MONO_LANGVERSIONSWITCH_35 := -langversion:3
DOTNETFRAMEWORK_MONO_LANGVERSIONSWITCH_30 := -langversion:ISO-2
DOTNETFRAMEWORK_MONO_LANGVERSIONSWITCH_20 := -langversion:ISO-2


